// This file was generated by the Pact Toolbox
import { PactTransactionBuilder, PactExecPayload } from "@pact-toolbox/transaction";

/**
 * A todo item
 */
export interface Todo {
  id: string;
  title: string;
  completed: boolean;
  deleted: boolean;
}

/**
 * Create new todo with ID and TITLE.
 */
export function createTodo(id: string, title: string): PactTransactionBuilder<PactExecPayload, string>;
/**
 * Toggle completed status flag for todo at ID.
 */
export function toggleTodo(id: string): PactTransactionBuilder<PactExecPayload, string>;
/**
 * Update todo at ID.
 */
export function updateTodo(id: string, title: string): PactTransactionBuilder<PactExecPayload, string>;
/**
 * Delete todo at ID (by setting deleted flag).
 */
export function deleteTodo(id: string): PactTransactionBuilder<PactExecPayload, string>;
/**
 * Get a single todo
 */
export function getTodo(id: string): PactTransactionBuilder<PactExecPayload, Todo>;
/**
 * Get all todos.
 */
export function getTodos(): PactTransactionBuilder<PactExecPayload, Todo[]>;

//# sourceMappingURL=todos.pact.d.ts.map