// THIS FILE IS AUTOGENERATED

import { PactExecPayload, PactUnsignedTransactionBuilder } from "@pact-toolbox/transaction";

export declare function test(name: string): PactUnsignedTransactionBuilder<PactExecPayload, unknown>;
