// THIS FILE IS AUTOGENERATED

  import { PactUnsignedTransactionBuilder, PactExecPayload } from '@pact-toolbox/client';

  export declare function test(name: string):PactUnsignedTransactionBuilder<PactExecPayload, unknown>;
