// THIS FILE IS AUTOGENERATED

import { PactExecPayload, PactUnsignedTransactionBuilder } from "@pact-toolbox/client";

export declare function sayHello(name: string): PactUnsignedTransactionBuilder<PactExecPayload, unknown>;
