// THIS FILE IS AUTOGENERATED

import { PactTransactionBuilder, PactExecPayload } from '@pact-toolbox/client';

export declare function sayHello(name: string): PactTransactionBuilder<PactExecPayload, unknown>;
