// THIS FILE IS AUTOGENERATED

import { PactExecPayload, PactTransactionBuilder } from "@pact-toolbox/client";

export declare function sayHello(name: string): PactTransactionBuilder<PactExecPayload, unknown>;
