on: [push]

jobs:
  todo_mvc:
    runs-on: ubuntu-latest
    name: Test TodoMVC in devnet
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Devnet
        uses: ./.github/actions/devnet
        with:
          script: |
            cd apps/todo-mvc
            pnpm pact:prelude
            pnpm test
          pwd:
        id: devnet
